name: My first Workflow
on:
    push:
      branches:
        - master

jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
            - name: "Greeting step"
              run: echo "Push the code"
